version: '3.9'

services:
  rethinkdb:
    image: rethinkdb:2.4
    ports:
      - 28015:28015
      - 8081:8081
    restart: always
    volumes:
      - ./server/db/exhibitions/data:/app
    networks:
      - net

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx4096m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./server/db/fulltext/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    networks:
      - net

  qdrant:
    image: qdrant/qdrant:latest
    mem_limit: 4096m
    ports:
      - 6333:6333
    volumes:
      - ./server/db/vectorspace/data:/qdrant/storage
    networks:
      - net

  server: 
    depends_on:
      - rethinkdb
      - elastic
      - qdrant
    build: 
      context: server
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    restart: always
    networks:
      - net

  nginx:
    depends_on: 
      - server
    image: nginx:latest
    ports: 
        - 80:80
        - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/www/:/var/www/:rw
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - net

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  net: