version: '3.9'

services:
  rethinkdb:
    image: rethinkdb:2.4
    ports:
      - 8081:8080
      - 28015:28015
    volumes:
      - ./db/exhibitions/data:/app
    networks:
      - net

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx4096m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./db/fulltext/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    networks:
      - net

  qdrant:
    image: generall/qdrant:latest
    mem_limit: 1024m
    ports:
      - 6333:6333
    volumes:
      - ./db/vectorspace/data:/qdrant/storage

networks:
  net: